Repository Tecnativa/doodba, pull requests merged in 2018-05, with the labels that each got.

#139 add DBFILTER to common environment
  .env
  common.yaml
Labels: enhancement, scaffolding, work in progress

#140 Upgrade to Node 6.x (LTS) and Less 2.x in all versions
  11.0.Dockerfile
  8.0.Dockerfile
Labels: docker image

#141 [DCK] Add gravatar proxy
  devel.yaml
  test.yaml
Labels: enhancement, qa, scaffolding

#143 [DCK] Add alternative domain redirection
  .env
  prod.yaml
Labels: enhancement, scaffolding

#144 Output failing addons once for all loop
  lib/odoobaselib/__init__.py
Labels: docker image, enhancement

#145 Main scaffolding is now 11.0
  tests/__init__.py
Labels: bug, docker image
