Repository Tecnativa/doodba, pull requests merged in 2018-02, with the labels that each got.

#126 Proxy for Odoo in devel
  devel.yaml
Labels: bug, scaffolding, work in progress

#127 [FIX] Freeze psycopg2 library
  bin/install.sh
Labels: docker image, enhancement, work in progress

#128 [DCK] Whitelist google fonts in test environment
  test.yaml
Labels: enhancement, scaffolding
